language: python
branches:
  only:
    - master
python:
  - "2.7"
sudo: false
install:
  - pip install sphinx
script: 
  - make clean && make html linkcheck
  
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: msspec/msspec.github.io
  target_branch: master
